######################################################################
# Automatically generated by qmake (3.0) Sat Aug 9 20:35:47 2014
######################################################################

TEMPLATE = app
TARGET = qt_client
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += statistics.h widget.h
SOURCES += main.cpp statistics.cpp widget.cpp
RESOURCES += avatars.qrc
