######################################################################
# Automatically generated by qmake (3.0) Sat Aug 9 20:35:47 2014
######################################################################

TEMPLATE = app
TARGET = server
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += statistics.h widget.h log.h \
    ../include/cin_sender.h \
    ../include/include.h
SOURCES += main.cpp statistics.cpp widget.cpp log.cpp \
    session.cpp
RESOURCES += avatars.qrc

FORMS += \
    Log.ui
